version: "3"
services:
    app:
        build: .
        depends_on:
            - db
        ports:
            - "5001:5001"
        links:
            - db
    db:
        image: mongo:latest
        ports:
            - "5000:27017"
        environment:
            - MONGO_INITDB_DATABASE=movies